# Generated by Django 4.1.7 on 2023-04-02 21:27

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("posts", "0002_remove_post_status"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="post",
            name="slug",
        ),
    ]
