# Generated by Django 4.1.7 on 2023-04-05 17:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("posts", "0003_remove_post_slug"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="post",
            options={"ordering": ("published",)},
        ),
        migrations.AlterField(
            model_name="post",
            name="category",
            field=models.CharField(
                choices=[
                    ("DRESSY", "Dressy"),
                    ("DRESSY_CAUSAL", "Dressy Casual"),
                    ("STREETWARE", "Streetware"),
                ],
                max_length=100,
            ),
        ),
    ]
