# Generated by Django 4.1.7 on 2023-04-05 19:26

from django.db import migrations, models
import django_mysql.models


class Migration(migrations.Migration):
    dependencies = [
        ("posts", "0004_alter_post_options_alter_post_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="category",
            field=django_mysql.models.ListCharField(
                models.CharField(
                    choices=[
                        ("DRESSY", "Dressy"),
                        ("DRESSY_CAUSAL", "Dressy Casual"),
                        ("STREETWARE", "Streetware"),
                    ],
                    max_length=25,
                ),
                max_length=130,
                size=5,
            ),
        ),
    ]
