version: "3"
services: 
  react-app:
    image: react-app
    ports: 
      - "3000:3000"
  app-server:
    image: app-server
    environment:
      - DATABASE_URL=mysql://root:password@mysql:3306/muda_workbench
    ports:
      - "8080:8080"
    depends_on:
      - mysql
  mysql:
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=muda_workbench
    ports:
      - "3306:3306"

